modLoader="javafml"
loaderVersion="[32,)" #forge version dep
issueTrackerURL="https://github.com/iChun/Death-Counter/issues"

[[mods]]
    modId="deathcounter"
    version="${file.jarVersion}" #mandatory
    displayName="Death Counter"
    displayURL="https://ichun.me/mods/death-counter/"
    authors="iChun"
    description='''
    Simple death counter for servers.
    '''

[[dependencies.deathcounter]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.deathcounter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,1.17)"
    ordering="NONE"
    side="BOTH"
